### ISSUE TITLE
Write submission for This Week in Rust

### ISSUE THREAD

**Issue by mcoblenz** [mojeanmac/vscode-salt#15]
Adapt what's already in the IRB protocol. Learn how to submit to TWiR and what the deadlines are.

**Comment by mojeanmac** [comment]
Researchers at the University of California, San Diego are conducting a research study on Rust errors and how we can help make it easier to learn Rust. We have developed a free Visual Studio Code extension, `Something` `Asomething` Language Tutor (SALT), which includes features that may be helpful while you’re learning Rust, such as REVIS, a borrowing and ownership error visualizer. If you grant permission, the extension can also send us data regarding the errors you’ve experienced while compiling Rust code; we plan to use that information to evaluate the impact of our extension as well as to give you feedback on your progress. If you are interested in helping, please install the extension through the Visual Studio Code Marketplace [link]. For more information, you can contact Michael Coblenz (mcoblenz@ucsd.edu).

Will do README tomorrow :)
